url: https://trestletrailtech.github.io
baseurl: 

# Site settings
title: Trestle Trail Technology
email: dusty.juhl@trestletrailtech.com
description: "Trestle Trail Technology provides software testing, agile coaching, and digital media management. Trestle Trail is based in Ankeny."


# Team names, titles and social links
people:
- name: Dusty Juhl
  pic: headshot_200x200
  position: Owner/President & Independent QA Consultant
  social:
    - title: facebook
      url: https://www.facebook.com/dustyjuhl
    - title: github
      url: https://www.github.com/dustyjuhl
    - title: linkedin
      url: https://www.linkedin.com/in/dustyjuhl
    - title: twitter
      url: https://twitter.com/dustyjuhl

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/TrestleTrailTech
  - title: github
    url: https://github.com/TrestleTrailTechnology
# - title: instagram
#   url:     
  - title: linkedin
    url: https://www.linkedin.com/company/trestle-trail-technology-llc/
# - title: pinterest
#   url: 
  - title: twitter
    url: https://twitter.com/TrestleTrailTec

# Postal address (add as many lines as necessary)
address:
  - line: 1600 NW Ridge Rd
  - line: Ankeny, IA 50023

# Build settings
markdown: kramdown
permalink: pretty
